### ISSUE TITLE
Is it possible to proxy requests to Seline?

### ISSUE THREAD

**Issue by beejaz** [getseline/seline-js#1]
Hi,

Is it possible to proxy the request from myserver.com/s/e to api.seline.so/s/e so the request isnt blocked by adblockers?

I tried to set it up with php proxy and using data-api-host="myserver.com" but forwarding all headers gave 403 Forbidden from Cloudflare and disable headers forwarding gave me 400 Bad request `{ error: "Invalid request."}`

**Comment by lo-ud** [comment]
hi @beejaz!
it's hard to debug like that, could you please send your proxy code?


make sure to also set a `data-token`

then also - we get country and ip from cloudflare headers, but if you're using your own proxy these values most likely will be lost. in this case, send us the following headers, it's easy to do if you're also using cloudflare:

`'Seline-IP'`  ---  we'll take ip value from it, acts the same as `'CF-Connecting-IP'`
`'Seline-Country'`  ---  we'll take country code value from it, acts the same as `'CF-IPCountry'`

if nothing works, please send the code and a link to your website

**Comment by beejaz** [comment]
Hi @lo-ud! 

Right now Im testing in localhost, I was thinking now that maybe that was the issue, if it forwards a "local ip" as `CF-Connecting-IP`?

Edit: It gives same error in both production and localhost.

I use this code in a `seline.php` file:
```
<?php
// Target URL (the external site)
$target_url = 'https://api.seline.so/s/e';

// Initialize a cURL session
$ch = curl_init($target_url);

// Forward all POST data
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, file_get_contents('php://input')); // Get the raw POST body
}

// Forward headers
$headers = [];
foreach (getallheaders() as $name => $value) {
    $headers[] = "$name: $value";
}
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

// Return the response from the target URL
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$response = curl_exec($ch);

// Get the status code and content type from the target response
$http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
$content_type = curl_getinfo($ch, CURLINFO_CONTENT_TYPE);

// Close the cURL session
curl_close($ch);

// Set the response code and content type
http_response_code($http_code);
header('Content-Type: ' . $content_type);

// Output the response body
echo $response;
```

And I use this code in `.htaccess`:
```
# Seline
RewriteCond %{REQUEST_METHOD} POST
RewriteRule ^s/e$ seline.php [L]
```

And I use this in `index.php` (I've added `localhost` as allowed host in seline settings):
```
<script async src="https://cdn.seline.so/seline.js" data-token="<token>" data-api-host="http://localhost"></script>
```

This is the POST request with HTTP 403:
```
POST http://localhost/s/e
{"token":"<token>","pathname":"/","referrer":null}
```

The response is from Cloudflare:
```
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

**Comment by lo-ud** [comment]
oh, that's cloudflare's 403
your server might be getting blocked by cloudflare's bot detection or something... but i'm not sure
we have a couple people proxying with their own servers and it works well.

do you have the same error on prod?

**Comment by beejaz** [comment]
Yes, same error on both prod & localhost unfortunately.

Ill try some different proxy code, Ill get back.

**Comment by beejaz** [comment]
@lo-ud I manage to get pass the 403 from Cloudflare but now I get 400 Bad Request from Seline server. Am I missing any required headers from my forwarded headers that you can think of?

```
$headers = [
    'content-Type' => 'application/json',
    'accept' => 'application/json, text/plain, */*',
    'user-agent' => 'axios/1.6.7',
    'accept-encoding' => "gzip, compress, deflate, br",
    'connection' => 'close',
    'Seline-IP' => '1.1.1.1',
    'Seline-Country' => 'SE'
];
```

**Comment by beejaz** [comment]
Alright, I found the issue, I needed to include the `origin` header otherwise it would fail with 400 Bad Request.

I dont have way to check the country of the visitor atm so all users would report as my server country which would not make sense in my stats so I will wait some more with the proxy setup before I use it.

**Comment by lo-ud** [comment]
ok!
the easiest would be to put your server behind cloudflare too and forward us ip and country
